[package]
name = "hpsdr-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
rand = "0.8"
rand_distr = "0.4"
num-complex = "0.4"
log = "0.4"
env_logger = "0.11"
